#ExternalChecksum("..\..\CodingCleanupWindow.xaml","{ff1816ec-aa5e-4d10-87f7-6f4963833460}","54C727425E97C9CB4D539B0C3BFFD5E231C3793C")
'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Diagnostics
Imports System.Windows
Imports System.Windows.Automation
Imports System.Windows.Controls
Imports System.Windows.Controls.Primitives
Imports System.Windows.Data
Imports System.Windows.Documents
Imports System.Windows.Ink
Imports System.Windows.Input
Imports System.Windows.Markup
Imports System.Windows.Media
Imports System.Windows.Media.Animation
Imports System.Windows.Media.Effects
Imports System.Windows.Media.Imaging
Imports System.Windows.Media.Media3D
Imports System.Windows.Media.TextFormatting
Imports System.Windows.Navigation
Imports System.Windows.Shapes
Imports System.Windows.Shell


'''<summary>
'''CodingCleanupWindow
'''</summary>
<Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>  _
Partial Public Class CodingCleanupWindow
    Inherits System.Windows.Window
    Implements System.Windows.Markup.IComponentConnector
    
    
    #ExternalSource("..\..\CodingCleanupWindow.xaml",28)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents NameFilterBox As System.Windows.Controls.TextBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\CodingCleanupWindow.xaml",42)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents ProcessAsmCheck As System.Windows.Controls.CheckBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\CodingCleanupWindow.xaml",47)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents ProcessPartCheck As System.Windows.Controls.CheckBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\CodingCleanupWindow.xaml",59)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents ExcludeVirtualCheck As System.Windows.Controls.CheckBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\CodingCleanupWindow.xaml",64)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents ExcludeStandardCheck As System.Windows.Controls.CheckBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\CodingCleanupWindow.xaml",69)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents ExcludePurchasedCheck As System.Windows.Controls.CheckBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\CodingCleanupWindow.xaml",76)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents ExecuteButton As System.Windows.Controls.Button
    
    #End ExternalSource
    
    Private _contentLoaded As Boolean
    
    '''<summary>
    '''InitializeComponent
    '''</summary>
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")>  _
    Public Sub InitializeComponent() Implements System.Windows.Markup.IComponentConnector.InitializeComponent
        If _contentLoaded Then
            Return
        End If
        _contentLoaded = true
        Dim resourceLocater As System.Uri = New System.Uri("/外部程序;component/codingcleanupwindow.xaml", System.UriKind.Relative)
        
        #ExternalSource("..\..\CodingCleanupWindow.xaml",1)
        System.Windows.Application.LoadComponent(Me, resourceLocater)
        
        #End ExternalSource
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes"),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity"),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")>  _
    Sub System_Windows_Markup_IComponentConnector_Connect(ByVal connectionId As Integer, ByVal target As Object) Implements System.Windows.Markup.IComponentConnector.Connect
        If (connectionId = 1) Then
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",13)
            AddHandler CType(target,CodingCleanupWindow).Loaded, New System.Windows.RoutedEventHandler(AddressOf Me.Window_Loaded)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 2) Then
            Me.NameFilterBox = CType(target,System.Windows.Controls.TextBox)
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",33)
            AddHandler Me.NameFilterBox.LostFocus, New System.Windows.RoutedEventHandler(AddressOf Me.NameFilterBox_LostFocus)
            
            #End ExternalSource
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",34)
            AddHandler Me.NameFilterBox.KeyDown, New System.Windows.Input.KeyEventHandler(AddressOf Me.NameFilterBox_KeyDown)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 3) Then
            Me.ProcessAsmCheck = CType(target,System.Windows.Controls.CheckBox)
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",45)
            AddHandler Me.ProcessAsmCheck.Checked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",46)
            AddHandler Me.ProcessAsmCheck.Unchecked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 4) Then
            Me.ProcessPartCheck = CType(target,System.Windows.Controls.CheckBox)
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",49)
            AddHandler Me.ProcessPartCheck.Checked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",50)
            AddHandler Me.ProcessPartCheck.Unchecked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 5) Then
            Me.ExcludeVirtualCheck = CType(target,System.Windows.Controls.CheckBox)
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",62)
            AddHandler Me.ExcludeVirtualCheck.Checked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",63)
            AddHandler Me.ExcludeVirtualCheck.Unchecked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 6) Then
            Me.ExcludeStandardCheck = CType(target,System.Windows.Controls.CheckBox)
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",67)
            AddHandler Me.ExcludeStandardCheck.Checked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",68)
            AddHandler Me.ExcludeStandardCheck.Unchecked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 7) Then
            Me.ExcludePurchasedCheck = CType(target,System.Windows.Controls.CheckBox)
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",71)
            AddHandler Me.ExcludePurchasedCheck.Checked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",72)
            AddHandler Me.ExcludePurchasedCheck.Unchecked, New System.Windows.RoutedEventHandler(AddressOf Me.SettingCheck_Changed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 8) Then
            Me.ExecuteButton = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\CodingCleanupWindow.xaml",81)
            AddHandler Me.ExecuteButton.Click, New System.Windows.RoutedEventHandler(AddressOf Me.ExecuteButton_Click)
            
            #End ExternalSource
            Return
        End If
        Me._contentLoaded = true
    End Sub
End Class

