#ExternalChecksum("..\..\Form1.xaml","{ff1816ec-aa5e-4d10-87f7-6f4963833460}","F492748ED6DB94F8308E2BE0143E2B3802662231")
'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Diagnostics
Imports System.Windows
Imports System.Windows.Automation
Imports System.Windows.Controls
Imports System.Windows.Controls.Primitives
Imports System.Windows.Data
Imports System.Windows.Documents
Imports System.Windows.Ink
Imports System.Windows.Input
Imports System.Windows.Markup
Imports System.Windows.Media
Imports System.Windows.Media.Animation
Imports System.Windows.Media.Effects
Imports System.Windows.Media.Imaging
Imports System.Windows.Media.Media3D
Imports System.Windows.Media.TextFormatting
Imports System.Windows.Navigation
Imports System.Windows.Shapes
Imports System.Windows.Shell


'''<summary>
'''Form1
'''</summary>
<Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>  _
Partial Public Class Form1
    Inherits System.Windows.Window
    Implements System.Windows.Markup.IComponentConnector
    
    
    #ExternalSource("..\..\Form1.xaml",30)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents filePrefixLabel As System.Windows.Controls.TextBlock
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",44)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents fileNameLabel As System.Windows.Controls.TextBlock
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",66)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents GroupBox1 As System.Windows.Controls.GroupBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",73)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button9 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",74)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button5 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",75)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button2 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",79)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents GroupBox3 As System.Windows.Controls.GroupBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",86)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button1 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",87)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button8 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",88)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button4 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",92)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents GroupBox2 As System.Windows.Controls.GroupBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",99)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button6 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",100)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button17 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",101)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button18 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",102)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button16 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",103)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button13 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",104)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button11 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",115)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button19 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",116)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button20 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",122)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button10 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",123)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button12 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\Form1.xaml",127)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents Button14 As System.Windows.Controls.Button
    
    #End ExternalSource
    
    Private _contentLoaded As Boolean
    
    '''<summary>
    '''InitializeComponent
    '''</summary>
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")>  _
    Public Sub InitializeComponent() Implements System.Windows.Markup.IComponentConnector.InitializeComponent
        If _contentLoaded Then
            Return
        End If
        _contentLoaded = true
        Dim resourceLocater As System.Uri = New System.Uri("/外部程序;component/form1.xaml", System.UriKind.Relative)
        
        #ExternalSource("..\..\Form1.xaml",1)
        System.Windows.Application.LoadComponent(Me, resourceLocater)
        
        #End ExternalSource
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes"),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity"),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")>  _
    Sub System_Windows_Markup_IComponentConnector_Connect(ByVal connectionId As Integer, ByVal target As Object) Implements System.Windows.Markup.IComponentConnector.Connect
        If (connectionId = 1) Then
            
            #ExternalSource("..\..\Form1.xaml",12)
            AddHandler CType(target,Form1).Loaded, New System.Windows.RoutedEventHandler(AddressOf Me.Form1_Load)
            
            #End ExternalSource
            
            #ExternalSource("..\..\Form1.xaml",13)
            AddHandler CType(target,Form1).SourceInitialized, New System.EventHandler(AddressOf Me.Form1_SourceInitialized)
            
            #End ExternalSource
            
            #ExternalSource("..\..\Form1.xaml",14)
            AddHandler CType(target,Form1).Closing, New System.ComponentModel.CancelEventHandler(AddressOf Me.Form1_Closing)
            
            #End ExternalSource
            
            #ExternalSource("..\..\Form1.xaml",15)
            AddHandler CType(target,Form1).Closed, New System.EventHandler(AddressOf Me.Form1_Closed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 2) Then
            Me.filePrefixLabel = CType(target,System.Windows.Controls.TextBlock)
            Return
        End If
        If (connectionId = 3) Then
            Me.fileNameLabel = CType(target,System.Windows.Controls.TextBlock)
            Return
        End If
        If (connectionId = 4) Then
            Me.GroupBox1 = CType(target,System.Windows.Controls.GroupBox)
            Return
        End If
        If (connectionId = 5) Then
            Me.Button9 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",73)
            AddHandler Me.Button9.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button9_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 6) Then
            Me.Button5 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",74)
            AddHandler Me.Button5.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button5_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 7) Then
            Me.Button2 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",75)
            AddHandler Me.Button2.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button2_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 8) Then
            Me.GroupBox3 = CType(target,System.Windows.Controls.GroupBox)
            Return
        End If
        If (connectionId = 9) Then
            Me.Button1 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",86)
            AddHandler Me.Button1.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button1_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 10) Then
            Me.Button8 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",87)
            AddHandler Me.Button8.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button8_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 11) Then
            Me.Button4 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",88)
            AddHandler Me.Button4.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button4_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 12) Then
            Me.GroupBox2 = CType(target,System.Windows.Controls.GroupBox)
            Return
        End If
        If (connectionId = 13) Then
            Me.Button6 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",99)
            AddHandler Me.Button6.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button6_Click_1)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 14) Then
            Me.Button17 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",100)
            AddHandler Me.Button17.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button17_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 15) Then
            Me.Button18 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",101)
            AddHandler Me.Button18.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button18_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 16) Then
            Me.Button16 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",102)
            AddHandler Me.Button16.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button16_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 17) Then
            Me.Button13 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",103)
            AddHandler Me.Button13.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button13_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 18) Then
            Me.Button11 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",104)
            AddHandler Me.Button11.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button11_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 19) Then
            Me.Button19 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",115)
            AddHandler Me.Button19.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button19_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 20) Then
            Me.Button20 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",116)
            AddHandler Me.Button20.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button20_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 21) Then
            Me.Button10 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",122)
            AddHandler Me.Button10.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button10_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 22) Then
            Me.Button12 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",123)
            AddHandler Me.Button12.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button12_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 23) Then
            Me.Button14 = CType(target,System.Windows.Controls.Button)
            
            #ExternalSource("..\..\Form1.xaml",133)
            AddHandler Me.Button14.Click, New System.Windows.RoutedEventHandler(AddressOf Me.Button14_Click_1)
            
            #End ExternalSource
            Return
        End If
        Me._contentLoaded = true
    End Sub
End Class

