#ExternalChecksum("..\..\PropertyOverlaySettingsWindow.xaml","{ff1816ec-aa5e-4d10-87f7-6f4963833460}","B209AC39EC56948011A68DCCC4BA760EA03A3CF5")
'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Diagnostics
Imports System.Windows
Imports System.Windows.Automation
Imports System.Windows.Controls
Imports System.Windows.Controls.Primitives
Imports System.Windows.Data
Imports System.Windows.Documents
Imports System.Windows.Ink
Imports System.Windows.Input
Imports System.Windows.Markup
Imports System.Windows.Media
Imports System.Windows.Media.Animation
Imports System.Windows.Media.Effects
Imports System.Windows.Media.Imaging
Imports System.Windows.Media.Media3D
Imports System.Windows.Media.TextFormatting
Imports System.Windows.Navigation
Imports System.Windows.Shapes
Imports System.Windows.Shell


'''<summary>
'''PropertyOverlaySettingsWindow
'''</summary>
<Microsoft.VisualBasic.CompilerServices.DesignerGenerated()>  _
Partial Public Class PropertyOverlaySettingsWindow
    Inherits System.Windows.Window
    Implements System.Windows.Markup.IComponentConnector
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",28)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents OpacityLabel As System.Windows.Controls.TextBlock
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",31)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents OpacitySlider As System.Windows.Controls.Slider
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",53)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents ColorCombo As System.Windows.Controls.ComboBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",67)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents DisplayModeCombo As System.Windows.Controls.ComboBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",92)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents PropSourceCombo As System.Windows.Controls.ComboBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",106)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents TopMostCheck As System.Windows.Controls.CheckBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",111)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents MouseThroughCheck As System.Windows.Controls.CheckBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",132)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents KeyList As System.Windows.Controls.ListBox
    
    #End ExternalSource
    
    
    #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",164)
    <System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")>  _
    Friend WithEvents NewKeyText As System.Windows.Controls.TextBox
    
    #End ExternalSource
    
    Private _contentLoaded As Boolean
    
    '''<summary>
    '''InitializeComponent
    '''</summary>
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")>  _
    Public Sub InitializeComponent() Implements System.Windows.Markup.IComponentConnector.InitializeComponent
        If _contentLoaded Then
            Return
        End If
        _contentLoaded = true
        Dim resourceLocater As System.Uri = New System.Uri("/外部程序;component/propertyoverlaysettingswindow.xaml", System.UriKind.Relative)
        
        #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",1)
        System.Windows.Application.LoadComponent(Me, resourceLocater)
        
        #End ExternalSource
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes"),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity"),  _
     System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")>  _
    Sub System_Windows_Markup_IComponentConnector_Connect(ByVal connectionId As Integer, ByVal target As Object) Implements System.Windows.Markup.IComponentConnector.Connect
        If (connectionId = 1) Then
            Me.OpacityLabel = CType(target,System.Windows.Controls.TextBlock)
            Return
        End If
        If (connectionId = 2) Then
            Me.OpacitySlider = CType(target,System.Windows.Controls.Slider)
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",36)
            AddHandler Me.OpacitySlider.ValueChanged, New System.Windows.RoutedPropertyChangedEventHandler(Of Double)(AddressOf Me.OpacitySlider_ValueChanged)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 3) Then
            Me.ColorCombo = CType(target,System.Windows.Controls.ComboBox)
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",56)
            AddHandler Me.ColorCombo.SelectionChanged, New System.Windows.Controls.SelectionChangedEventHandler(AddressOf Me.Combo_SelectionChanged)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 4) Then
            Me.DisplayModeCombo = CType(target,System.Windows.Controls.ComboBox)
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",70)
            AddHandler Me.DisplayModeCombo.SelectionChanged, New System.Windows.Controls.SelectionChangedEventHandler(AddressOf Me.Combo_SelectionChanged)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 5) Then
            Me.PropSourceCombo = CType(target,System.Windows.Controls.ComboBox)
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",95)
            AddHandler Me.PropSourceCombo.SelectionChanged, New System.Windows.Controls.SelectionChangedEventHandler(AddressOf Me.Combo_SelectionChanged)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 6) Then
            Me.TopMostCheck = CType(target,System.Windows.Controls.CheckBox)
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",109)
            AddHandler Me.TopMostCheck.Checked, New System.Windows.RoutedEventHandler(AddressOf Me.CheckBox_Changed)
            
            #End ExternalSource
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",110)
            AddHandler Me.TopMostCheck.Unchecked, New System.Windows.RoutedEventHandler(AddressOf Me.CheckBox_Changed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 7) Then
            Me.MouseThroughCheck = CType(target,System.Windows.Controls.CheckBox)
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",113)
            AddHandler Me.MouseThroughCheck.Checked, New System.Windows.RoutedEventHandler(AddressOf Me.CheckBox_Changed)
            
            #End ExternalSource
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",114)
            AddHandler Me.MouseThroughCheck.Unchecked, New System.Windows.RoutedEventHandler(AddressOf Me.CheckBox_Changed)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 8) Then
            Me.KeyList = CType(target,System.Windows.Controls.ListBox)
            Return
        End If
        If (connectionId = 9) Then
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",146)
            AddHandler CType(target,System.Windows.Controls.Button).Click, New System.Windows.RoutedEventHandler(AddressOf Me.UpButton_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 10) Then
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",153)
            AddHandler CType(target,System.Windows.Controls.Button).Click, New System.Windows.RoutedEventHandler(AddressOf Me.DownButton_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 11) Then
            Me.NewKeyText = CType(target,System.Windows.Controls.TextBox)
            Return
        End If
        If (connectionId = 12) Then
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",183)
            AddHandler CType(target,System.Windows.Controls.Button).Click, New System.Windows.RoutedEventHandler(AddressOf Me.AddButton_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 13) Then
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",189)
            AddHandler CType(target,System.Windows.Controls.Button).Click, New System.Windows.RoutedEventHandler(AddressOf Me.DeleteButton_Click)
            
            #End ExternalSource
            Return
        End If
        If (connectionId = 14) Then
            
            #ExternalSource("..\..\PropertyOverlaySettingsWindow.xaml",198)
            AddHandler CType(target,System.Windows.Controls.Button).Click, New System.Windows.RoutedEventHandler(AddressOf Me.CloseButton_Click)
            
            #End ExternalSource
            Return
        End If
        Me._contentLoaded = true
    End Sub
End Class

